export interface City {
  name: string
  areas: string[]
}

export const EG_CITIES: City[] = [
  {
    name: 'Cairo',
    areas: [
      'Zamalek',
      'Nasr City',
      'Heliopolis',
      'Maadi',
      'New Cairo',
      'Mokattam',
      'Shubra',
      'Downtown',
      'Garden City',
      'Dokki',
      'Mohandessin',
      'Agouza',
      'Giza',
      '6th October',
      'Sheikh Zayed',
      'Haram',
      'Faisal',
      'Imbaba',
      'Bulaq',
      'Ain Shams',
      'Matariya',
      'Helwan',
      '15th May',
      'Badr City',
      'Shorouk City',
      'Rehab City',
      'Madinaty',
      'Future City',
      'Capital Gardens',
      'Al Rehab',
    ],
  },
  {
    name: 'Alexandria',
    areas: [
      'Smouha',
      'Roushdy',
      'San Stefano',
      'Sidi Gaber',
      'Sporting',
      'Miami',
      'Gleem',
      'Stanley',
      'Ras El Tin',
      'Montaza',
      'Sidi Bishr',
      'Mandara',
      'Victoria',
      'Bolkly',
      'Raml Station',
      'Downtown',
      'Karmoz',
      'Agami',
      'Borg El Arab',
      'New Borg El Arab',
      'Abu Qir',
      'Dekheila',
      'Amreya',
      'Borg El Arab City',
    ],
  },
  {
    name: 'Giza',
    areas: [
      'Dokki',
      'Agouza',
      'Giza',
      '6th October',
      'Sheikh Zayed',
      'Haram',
      'Faisal',
      'Imbaba',
      'Bulaq El Dakrour',
      'El Omraniya',
      'El Warraq',
      'El Ayyat',
      'El Badrasheen',
      'El Saff',
      'El Hawamdeya',
      'El Kerdasa',
      'El Mansouriya',
      'El Nahya',
      'El Saff',
      'El Talbia',
      'El Warraq',
      'El Zawya El Hamra',
    ],
  },
  {
    name: 'Qalyubia',
    areas: [
      'Shubra El Kheima',
      'Qalyub',
      'Banha',
      'Toukh',
      'Qaha',
      'El Khanka',
      'El Obour',
      'El Shorouk',
      'El Mostakbal',
      'El Salam',
      'El Marg',
      'El Khanka',
      'El Qanater El Khayreya',
      'El Qanater',
      'El Khanka',
      'El Obour',
      'El Shorouk',
      'El Mostakbal',
      'El Salam',
      'El Marg',
    ],
  },
  {
    name: 'Gharbia',
    areas: [
      'Tanta',
      'Mahalla El Kubra',
      'Kafr El Zayat',
      'Zefta',
      'Basyoun',
      'Qutur',
      'Samanoud',
      'El Santa',
      'El Mahalla El Kubra',
      'El Kafr El Zayat',
      'El Zefta',
      'El Basyoun',
      'El Qutur',
      'El Samanoud',
      'El Santa',
    ],
  },
  {
    name: 'Dakahlia',
    areas: [
      'Mansoura',
      'Talkha',
      'Mit Ghamr',
      'Dekernes',
      'Aga',
      'El Senbellawein',
      'El Gamaliya',
      'El Matareya',
      'El Manzala',
      'El Gamaliya',
      'El Matareya',
      'El Manzala',
      'El Senbellawein',
      'El Gamaliya',
      'El Matareya',
      'El Manzala',
    ],
  },
  {
    name: 'Sharqia',
    areas: [
      'Zagazig',
      '10th of Ramadan',
      'Abu Hammad',
      'Abu Kebir',
      'Belbeis',
      'Diyarb Negm',
      'Faqous',
      'Hihya',
      'Kafr Saqr',
      'Mashtool El Souk',
      'Minya El Qamh',
      'Qanayat',
      'Qenayat',
      'Qenayat El Khair',
      'Qenayat El Khair',
      'Qenayat El Khair',
    ],
  },
  {
    name: 'Monufia',
    areas: [
      'Shibin El Kom',
      'Tala',
      'Ashmoun',
      'Berket El Saba',
      'El Bagour',
      'El Qanatir El Khayreya',
      'El Qanatir El Khayreya',
      'El Qanatir El Khayreya',
      'El Qanatir El Khayreya',
      'El Qanatir El Khayreya',
      'El Qanatir El Khayreya',
      'El Qanatir El Khayreya',
      'El Qanatir El Khayreya',
      'El Qanatir El Khayreya',
      'El Qanatir El Khayreya',
    ],
  },
  {
    name: 'Beheira',
    areas: [
      'Damanhur',
      'Kafr El Dawwar',
      'Rashid',
      'Abu El Matameer',
      'Abu Hummus',
      'El Delengat',
      'El Mahmoudiya',
      'El Rahmaniya',
      'El Wadi El Gedid',
      'El Wadi El Gedid',
      'El Wadi El Gedid',
      'El Wadi El Gedid',
      'El Wadi El Gedid',
      'El Wadi El Gedid',
      'El Wadi El Gedid',
    ],
  },
  {
    name: 'Kafr El Sheikh',
    areas: [
      'Kafr El Sheikh',
      'Desouk',
      'Fuwa',
      'Baltim',
      'El Hamool',
      'El Reyad',
      'El Reyad',
      'El Reyad',
      'El Reyad',
      'El Reyad',
      'El Reyad',
      'El Reyad',
      'El Reyad',
      'El Reyad',
      'El Reyad',
    ],
  },
  {
    name: 'Damietta',
    areas: [
      'Damietta',
      'New Damietta',
      'Ras El Bar',
      'El Zarqa',
      'El Zarqa',
      'El Zarqa',
      'El Zarqa',
      'El Zarqa',
      'El Zarqa',
      'El Zarqa',
      'El Zarqa',
      'El Zarqa',
      'El Zarqa',
      'El Zarqa',
      'El Zarqa',
    ],
  },
  {
    name: 'Port Said',
    areas: [
      'Port Said',
      'Port Fuad',
      'Port Fuad',
      'Port Fuad',
      'Port Fuad',
      'Port Fuad',
      'Port Fuad',
      'Port Fuad',
      'Port Fuad',
      'Port Fuad',
      'Port Fuad',
      'Port Fuad',
      'Port Fuad',
      'Port Fuad',
      'Port Fuad',
    ],
  },
  {
    name: 'Ismailia',
    areas: [
      'Ismailia',
      'Fayed',
      'El Qantara',
      'El Qantara',
      'El Qantara',
      'El Qantara',
      'El Qantara',
      'El Qantara',
      'El Qantara',
      'El Qantara',
      'El Qantara',
      'El Qantara',
      'El Qantara',
      'El Qantara',
      'El Qantara',
    ],
  },
  {
    name: 'Suez',
    areas: [
      'Suez',
      'Suez',
      'Suez',
      'Suez',
      'Suez',
      'Suez',
      'Suez',
      'Suez',
      'Suez',
      'Suez',
      'Suez',
      'Suez',
      'Suez',
      'Suez',
      'Suez',
    ],
  },
  {
    name: 'North Sinai',
    areas: [
      'El Arish',
      'Sheikh Zuweid',
      'Rafah',
      'Rafah',
      'Rafah',
      'Rafah',
      'Rafah',
      'Rafah',
      'Rafah',
      'Rafah',
      'Rafah',
      'Rafah',
      'Rafah',
      'Rafah',
      'Rafah',
    ],
  },
  {
    name: 'South Sinai',
    areas: [
      'Sharm El Sheikh',
      'Dahab',
      'Nuweiba',
      'Taba',
      'Taba',
      'Taba',
      'Taba',
      'Taba',
      'Taba',
      'Taba',
      'Taba',
      'Taba',
      'Taba',
      'Taba',
      'Taba',
    ],
  },
  {
    name: 'Red Sea',
    areas: [
      'Hurghada',
      'El Gouna',
      'Safaga',
      'Marsa Alam',
      'Marsa Alam',
      'Marsa Alam',
      'Marsa Alam',
      'Marsa Alam',
      'Marsa Alam',
      'Marsa Alam',
      'Marsa Alam',
      'Marsa Alam',
      'Marsa Alam',
      'Marsa Alam',
      'Marsa Alam',
    ],
  },
  {
    name: 'Luxor',
    areas: [
      'Luxor',
      'Karnak',
      'Karnak',
      'Karnak',
      'Karnak',
      'Karnak',
      'Karnak',
      'Karnak',
      'Karnak',
      'Karnak',
      'Karnak',
      'Karnak',
      'Karnak',
      'Karnak',
      'Karnak',
    ],
  },
  {
    name: 'Aswan',
    areas: [
      'Aswan',
      'Abu Simbel',
      'Abu Simbel',
      'Abu Simbel',
      'Abu Simbel',
      'Abu Simbel',
      'Abu Simbel',
      'Abu Simbel',
      'Abu Simbel',
      'Abu Simbel',
      'Abu Simbel',
      'Abu Simbel',
      'Abu Simbel',
      'Abu Simbel',
      'Abu Simbel',
    ],
  },
  {
    name: 'New Valley',
    areas: [
      'Kharga',
      'Dakhla',
      'Dakhla',
      'Dakhla',
      'Dakhla',
      'Dakhla',
      'Dakhla',
      'Dakhla',
      'Dakhla',
      'Dakhla',
      'Dakhla',
      'Dakhla',
      'Dakhla',
      'Dakhla',
      'Dakhla',
    ],
  },
  {
    name: 'Matrouh',
    areas: [
      'Mersa Matruh',
      'El Alamein',
      'El Alamein',
      'El Alamein',
      'El Alamein',
      'El Alamein',
      'El Alamein',
      'El Alamein',
      'El Alamein',
      'El Alamein',
      'El Alamein',
      'El Alamein',
      'El Alamein',
      'El Alamein',
      'El Alamein',
    ],
  },
]

export function getAreasByCity(cityName: string): string[] {
  const city = EG_CITIES.find(c => c.name === cityName)
  return city?.areas || []
}

export function getAllCities(): string[] {
  return EG_CITIES.map(city => city.name)
}
