export interface City {
  name: string;
  areas: string[];
}

export const EG_CITIES: City[] = [
  {
    name: 'Cairo',
    areas: [
      'Zamalek',
      'Nasr City',
      'Heliopolis',
      'Maadi',
      'New Cairo',
      'Mokattam',
      'Shubra',
      'Downtown',
      'Garden City',
      'Dokki',
      'Agouza',
      'Mohandessin',
      'Helwan',
      'Ain Shams',
      'Shoubra El Kheima',
      'Hadayek El Kobba',
      'Manshiyat Naser',
      'El Matareya',
      'Zeitoun',
      'Abbassia',
    ],
  },
  {
    name: 'Alexandria',
    areas: [
      'Smouha',
      'Roushdy',
      'San Stefano',
      'Sidi Gaber',
      'Sporting',
      'Miami',
      'Gleem',
      'Camp Caesar',
      'Montaza',
      'Mandara',
      'Agami',
      'Hannoville',
      'Sidi Bishr',
      'Victoria',
      'Cleopatra',
      'Stanley',
    ],
  },
  {
    name: 'Giza',
    areas: [
      'Pyramids',
      'Sheikh Zayed',
      '6th of October',
      'Haram',
      'Faisal',
      'Imbaba',
      'Bulaq El Dakrour',
      'Kit Kat',
      'Agouza',
      'Dokki',
      'Mohandessin',
      'Omraniya',
      'Warraq',
      'Ausim',
    ],
  },
  {
    name: 'Qalyubia',
    areas: [
      'Benha',
      'Shubra El Kheima',
      'Qaha',
      'Khanka',
      'Shibin El Qanater',
      'Toukh',
      'Kafr Shukr',
      'Obour City',
      'Khosous',
      'Qalub',
    ],
  },
  {
    name: 'Sharqia',
    areas: [
      'Zagazig',
      '10th of Ramadan',
      'Bilbeis',
      'Minya El Qamh',
      'Abu Hammad',
      'Faqous',
      'Kafr Saqr',
      'Awlad Saqr',
      'Deirb Negm',
      'Hehya',
      'Abu Kabir',
      'Mashtool El Souk',
      'San El Hagar El Qiblia',
    ],
  },
  {
    name: 'Dakahlia',
    areas: [
      'Mansoura',
      'Talkha',
      'Mit Ghamr',
      'Dekernes',
      'Aga',
      'Manzala',
      'Temay El Amdid',
      'Sherbin',
      'Matariya',
      'Belqas',
      'Meet Salsil',
      'Gamasa',
      'Nabaroh',
      'Minyet El Nasr',
      'Tami El Zahayra',
    ],
  },
  {
    name: 'Beheira',
    areas: [
      'Damanhour',
      'Kafr El Dawar',
      'Rashid',
      'Edko',
      'Abu Hummus',
      'Abu El Matamer',
      'Delengat',
      'Mahmoudiyah',
      'Rahmaniyah',
      'Itay El Baroud',
      'Housh Eissa',
      'Shubrakhit',
      'Kom Hamada',
      'Badr',
      'Wadi El Natrun',
    ],
  },
  {
    name: 'Kafr El Sheikh',
    areas: [
      'Kafr El Sheikh',
      'Desouk',
      'Foua',
      'Metoubes',
      'Burg El Burullus',
      'Baltim',
      'Masief Baltim',
      'Hamoul',
      'Biyala',
      'Riyadh',
      'Sidi Salem',
    ],
  },
  {
    name: 'Gharbia',
    areas: [
      'Tanta',
      'El Mahalla El Kubra',
      'Kafr El Zayat',
      'Zefta',
      'Samannoud',
      'Bassioun',
      'Kotoor',
      'Qotour',
    ],
  },
  {
    name: 'Monufia',
    areas: [
      'Shibin El Kom',
      'Menouf',
      'Sadat City',
      'Ashmoun',
      'El Bagour',
      'Tala',
      'Quesna',
      'Berket El Sabaa',
      'Sers El Lyan',
    ],
  },
];

export function getCityByName(name: string): City | undefined {
  return EG_CITIES.find(city => city.name.toLowerCase() === name.toLowerCase());
}

export function getAreasByCity(cityName: string): string[] {
  const city = getCityByName(cityName);
  return city ? city.areas : [];
}