export { TamaguiProvider, View, Text } from '@tamagui/core'
export { default as config } from './tamagui.config'
export type { Conf } from './tamagui.config'
export { SharedButton } from './components/SharedButton'
export { TamaguiTest } from './components/TamaguiTest'
export { MyComponent } from './components/MyComponent'
export { CalendarComponent } from './components/CalendarComponent'
export { SafeText } from './components/SafeText'
export { filterDOMProps, createSafeComponent } from './utils/filterDOMProps'